export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
  },
  LEADS: {
    BASE: '/leads',
    BY_ID: (id: string) => `/leads/${id}`,
    TIMELINE: (id: string) => `/leads/${id}/timeline`,
    NOTES: (id: string) => `/leads/${id}/notes`,
    PROPERTY_SUGGESTIONS: (id: string) => `/leads/${id}/property-suggestions`,
    LINKED_PROPERTIES: (id: string) => `/leads/${id}/linked-properties`,
    LINKED_PROPERTY: (leadId: string, propertyId: string | number) =>
      `/leads/${leadId}/linked-properties/${propertyId}`,
  },
  CONTACTS: {
    BASE: '/contacts',
    BY_ID: (id: number | string) => `/contacts/${id}`,
    IMPORT_PREVIEW: '/contacts/import/preview',
    IMPORT: '/contacts/import',
  },
  WHATSAPP: {
    SETTINGS: '/whatsapp/settings',
    TEMPLATES: '/whatsapp/templates',
    TEMPLATE_BY_ID: (id: number | string) => `/whatsapp/templates/${id}`,
    SEND: '/whatsapp/send',
  },
  PROPERTIES: {
    BASE: '/properties',
    INVENTORY: '/properties/inventory',
    OWNERS: '/properties/owners',
    BY_ID: (id: string) => `/properties/${id}`,
    IMAGES: (id: string) => `/properties/${id}/images`,
    IMAGES_BATCH: (id: string) => `/properties/${id}/images/batch`,
  },
  PROPERTY_LOOKUPS: {
    BASE: '/property-lookups',
  },
  SITE_VISITS: {
    BASE: '/site-visits',
    BY_ID: (id: string) => `/site-visits/${id}`,
  },
  BOOKINGS: {
    BASE: '/bookings',
    BY_ID: (id: string) => `/bookings/${id}`,
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
  },
  ROLES: {
    BASE: '/roles',
  },
  LEAD_SOURCES: {
    BASE: '/lead-sources',
  },
  REPORTS: {
    LEAD_CONVERSION: '/reports/lead-conversion',
    SALES: '/reports/sales',
    REVENUE: '/reports/revenue',
    AGENT_PERFORMANCE: '/reports/agent-performance',
  },
  ORGANIZATIONS: {
    CURRENT: '/organizations/current',
    LOGO: '/organizations/current/logo',
    FAVICON: '/organizations/current/favicon',
  },
  MARKETING: {
    DASHBOARD: '/marketing/dashboard',
    SETTINGS: '/marketing/settings',
    GOOGLE_LOGIN: '/marketing/google/login',
    GOOGLE_DISCONNECT: '/marketing/google/disconnect',
    REVIEWS: '/marketing/google/reviews',
    REVIEWS_SYNC: '/marketing/google/reviews/sync',
    REVIEW: (id: string | number) => `/marketing/google/reviews/${id}`,
    REVIEW_GENERATE_AI: (id: string | number) => `/marketing/google/reviews/${id}/generate-ai`,
    REVIEW_REPLY: (id: string | number) => `/marketing/google/reviews/${id}/reply`,
    CONTENT: '/marketing/content',
    CONTENT_UPLOAD: '/marketing/content/upload',
    CONTENT_ITEM: (id: string | number) => `/marketing/content/${id}`,
    CONTENT_PUBLISH: (id: string | number) => `/marketing/content/${id}/publish`,
    CONTENT_SCHEDULE: (id: string | number) => `/marketing/content/${id}/schedule`,
    CAMPAIGNS: '/marketing/campaigns',
    CAMPAIGN: (id: string | number) => `/marketing/campaigns/${id}`,
    CAMPAIGN_PAUSE: (id: string | number) => `/marketing/campaigns/${id}/pause`,
    CAMPAIGN_RESUME: (id: string | number) => `/marketing/campaigns/${id}/resume`,
    ANALYTICS_REVIEWS: '/marketing/analytics/reviews',
    ANALYTICS_POSTS: '/marketing/analytics/posts',
  },
} as const
