/** Curated master data for Durga Property / Gurgaon listings — keeps CRM + website SEO consistent. */

export const GURGAON_CITIES = ['Gurgaon'] as const
export const HARYANA_STATES = ['Haryana'] as const

export const GURGAON_LOCALITIES = [
  // DLF
  'DLF Phase 1',
  'DLF Phase 2',
  'DLF Phase 3',
  'DLF Phase 4',
  'DLF Phase 5',

  // Major Roads / Corridors
  'Golf Course Road',
  'Golf Course Extension Road',
  'Sohna Road',
  'Dwarka Expressway',
  'Northern Peripheral Road',
  'Southern Peripheral Road',
  'MG Road',
  'Faridabad-Gurgaon Road',

  // Central Gurgaon
  'Sushant Lok 1',
  'Sushant Lok 2',
  'Sushant Lok 3',
  'South City 1',
  'South City 2',
  'Nirvana Country',
  'Huda City Centre',
  'Sector 14',
  'Sector 15',
  'Sector 17',
  'Sector 18',
  'Sector 21',
  'Sector 22',
  'Sector 23',
  'Sector 23A',
  'Sector 24',
  'Sector 25',
  'Sector 26',
  'Sector 27',
  'Sector 28',
  'Sector 29',
  'Sector 30',
  'Sector 31',
  'Sector 32',
  'Sector 33',
  'Sector 38',
  'Sector 39',
  'Sector 40',
  'Sector 41',
  'Sector 42',
  'Sector 43',
  'Sector 44',
  'Sector 45',
  'Sector 46',
  'Sector 47',
  'Sector 48',
  'Sector 49',
  'Sector 50',
  'Sector 51',
  'Sector 52',
  'Sector 53',
  'Sector 54',
  'Sector 55',
  'Sector 56',
  'Sector 57',
  'Sector 58',
  'Sector 59',
  'Sector 60',
  'Sector 61',
  'Sector 62',
  'Sector 63',
  'Sector 64',
  'Sector 65',
  'Sector 66',
  'Sector 67',
  'Sector 68',
  'Sector 69',
  'Sector 70',
  'Sector 71',
  'Sector 72',
  'Sector 73',
  'Sector 74',
  'Sector 75',
  'Sector 76',
  'Sector 77',
  'Sector 78',
  'Sector 79',
  'Sector 80',

  // New Gurgaon
  'New Gurgaon',
  'Sector 81',
  'Sector 82',
  'Sector 83',
  'Sector 84',
  'Sector 85',
  'Sector 86',
  'Sector 87',
  'Sector 88',
  'Sector 89',
  'Sector 90',
  'Sector 91',
  'Sector 92',
  'Sector 93',
  'Sector 93A',
  'Sector 94',
  'Sector 95',
  'Sector 95A',
  'Sector 96',
  'Sector 97',
  'Sector 98',
  'Sector 99',
  'Sector 100',
  'Sector 101',
  'Sector 102',
  'Sector 103',
  'Sector 104',
  'Sector 105',
  'Sector 106',
  'Sector 107',
  'Sector 108',
  'Sector 109',
  'Sector 110',
  'Sector 111',
  'Sector 112',
  'Sector 113',
  'Sector 114',
  'Sector 115',

  // Major Residential Localities
  'Palam Vihar',
  'Carterpuri',
  'Ashok Vihar',
  'Rajendra Park',
  'Laxman Vihar',
  'Jyoti Park',
  'Shivaji Nagar',
  'New Palam Vihar',
  'Basai',
  'Kadipur',
  'Wazirabad',
  'Nathupur',
  'Chakkarpur',
  'Sikanderpur',
  'Dundahera',
  'Saraswati Vihar',
  'Arjun Nagar',
  'Civil Lines',
  'Model Town',

  // Commercial / Business Districts
  'Cyber City',
  'Udyog Vihar',
  'Golf Course Road Business District',
  'Sector 44',
  'Sector 32',
  'Sector 18',
  'Sector 29',
  'Sohna Road Commercial Belt',

  // Emerging / Peripheral Gurgaon
  'Manesar',
  'IMT Manesar',
  'Kherki Daula',
  'Gurgaon-Farukhnagar Road',
  'Gwal Pahari',
  'Bandhwari',
  'Bhondsi',
  'Sohna',
  'Badshahpur',
  'Tikri',
  'Kadarpur',
  'Behrampur',
  'Dhamdama',
  'Fazilpur',
  'Nangli Umarpur',
  'Sector 70A',
  'Sector 71',
  'Sector 75A',
  'Sector 76A',
  'Sector 77A',
  'Sector 79A',
] as const

export const GURGAON_SECTORS = [
  'Sector 1',
  'Sector 2',
  'Sector 3',
  'Sector 4',
  'Sector 5',
  'Sector 6',
  'Sector 7',
  'Sector 8',
  'Sector 9',
  'Sector 9A',
  'Sector 10',
  'Sector 10A',
  'Sector 11',
  'Sector 12',
  'Sector 12A',
  'Sector 13',
  'Sector 14',
  'Sector 15',
  'Sector 15 Part 1',
  'Sector 15 Part 2',
  'Sector 17',
  'Sector 17A',
  'Sector 17B',
  'Sector 18',
  'Sector 21',
  'Sector 22',
  'Sector 22A',
  'Sector 23',
  'Sector 23A',
  'Sector 24',
  'Sector 25',
  'Sector 26',
  'Sector 26A',
  'Sector 27',
  'Sector 28',
  'Sector 29',
  'Sector 30',
  'Sector 31',
  'Sector 32',
  'Sector 33',
  'Sector 34',
  'Sector 35',
  'Sector 36',
  'Sector 36A',
  'Sector 37',
  'Sector 37A',
  'Sector 37B',
  'Sector 37C',
  'Sector 37D',
  'Sector 38',
  'Sector 38A',
  'Sector 39',
  'Sector 40',
  'Sector 41',
  'Sector 42',
  'Sector 43',
  'Sector 44',
  'Sector 45',
  'Sector 46',
  'Sector 47',
  'Sector 48',
  'Sector 49',
  'Sector 50',
  'Sector 51',
  'Sector 52',
  'Sector 53',
  'Sector 54',
  'Sector 55',
  'Sector 56',
  'Sector 57',
  'Sector 58',
  'Sector 59',
  'Sector 60',
  'Sector 61',
  'Sector 62',
  'Sector 63',
  'Sector 64',
  'Sector 65',
  'Sector 66',
  'Sector 67',
  'Sector 68',
  'Sector 69',
  'Sector 70',
  'Sector 71',
  'Sector 72',
  'Sector 73',
  'Sector 74',
  'Sector 75',
  'Sector 76',
  'Sector 77',
  'Sector 78',
  'Sector 79',
  'Sector 80',
  'Sector 81',
  'Sector 82',
  'Sector 83',
  'Sector 84',
  'Sector 85',
  'Sector 86',
  'Sector 87',
  'Sector 88',
  'Sector 89',
  'Sector 90',
  'Sector 91',
  'Sector 92',
  'Sector 93',
  'Sector 93A',
  'Sector 94',
  'Sector 95',
  'Sector 95A',
  'Sector 96',
  'Sector 97',
  'Sector 98',
  'Sector 99',
  'Sector 100',
  'Sector 101',
  'Sector 102',
  'Sector 103',
  'Sector 104',
  'Sector 105',
  'Sector 106',
  'Sector 107',
  'Sector 108',
  'Sector 109',
  'Sector 110',
  'Sector 111',
  'Sector 112',
  'Sector 113',
  'Sector 114',
  'Sector 115',
] as const

export const GURGAON_PINCODES = [
  '122001',
  '122002',
  '122003',
  '122004',
  '122005',
  '122006',
  '122007',
  '122008',
  '122009',
  '122010',
  '122011',
  '122012',
  '122015',
  '122016',
  '122017',
  '122018',
  '122051',
  '122052',
  '122101',
  '122102',
  '122103',
] as const

export const GURGAON_LANDMARKS = [
  'Cyber Hub',
  'Ambience Mall',
  'MG Road Metro Station',
  'IFFCO Chowk',
  'Golf Course Extension Road',
  'Sohna Road Junction',
  'Huda City Centre Metro',
  'World Mark Mall',
  'South Point Mall',
  'Good Earth City Centre',
  'Galleria Market',
  'Golf Course Road',
  'Dwarka Expressway Junction',
  'NH-48',
  'Rajiv Chowk',
  'Hero Honda Chowk',
  'None / Not Applicable',
] as const

export const GURGAON_BUILDERS = [
  // =========================
  // Major / Premium Developers
  // =========================
  'DLF Limited',
  'M3M India',
  'Godrej Properties',
  'Emaar India',
  'Sobha Limited',
  'Tata Housing',
  'ATS Infrastructure',
  'Adani Realty',
  'Mahindra Lifespaces',
  'Experion Developers',
  'BPTP Limited',
  'Signature Global',
  'Vatika Group',
  'Central Park',
  'Elan Group',

  // =========================
  // Established Gurgaon Developers
  // =========================
  'Tulip Infratech',
  'SS Group',
  'Bestech Group',
  'Conscient Infrastructure',
  'Ansal API',
  'Ansal Housing',
  'Raheja Developers',
  'Unitech Group',
  'IREO',
  'Puri Constructions',
  'Paras Buildtech',
  'Spaze Group',
  'Trehan Iris',
  'AIPL',
  'Suncity Projects',
  'Pioneer Urban',
  'Ambience Group',
  'Supertech Limited',
  'CHD Developers',
  'Krisumi Corporation',
  'ILD Group',
  'Mapsko Group',
  'Abw Infrastructure',
  'Imperia Group',
  'Corona Group',
  'Orchid Infrastructure',
  'RPS Group',
  'Earth Infrastructure',
  'Ramprastha Group',
  'Alpha Corp',
  'Landmark Group',
  'M3M',
  'JMD Group',
  'Bestech',
  'Global Group',
  'Crescent Group',

  // =========================
  // New / Emerging Developers
  // =========================
  'Smartworld Developers',
  'Ganga Realty',
  'Whiteland Corporation',
  'NeoLiv',
  'Navraj Group',
  'JMS Group',
  'ROF Group',
  'TARC',
  'Birla Estates',
  'Max Estates',
  'Ashiana Housing',
  'Dhoot Group',
  'HCBS Developments',
  'Trinity Group',
  'Trident Realty',
  'Trehan Group',
  'Krisumi',
  'M3M Hurun',
  'M3M India Private Limited',
  'Sohna Builders',
  'Conscient',
  'Aarcity Group',
  'Baani Group',
  'BPTP',
  'Pyramid Infratech',
  'Pyramid Group',
  'Signature Builders',
  'JMK Holdings',
  'Sare Homes',
  'Sare Realty',
  'Spire Edge',
  'Spire Group',
  'Ansal API',
  'Ansal Housing',
  'Raheja',
  'Raheja Vanya',
  'Emaar MGF',
  'Emperium',
  'Adore Realtech',
  'Apex Buildwell',
  'Crescent Parc',
  'M3M Group',
  'Gurgaon One',
  'VSR Ventures',
  'VSR Infrastructures',
  'Sapphire Builders',
  'KPDK Buildtech',
  'KPDK',
  'RPS Infrastructure',
  'RPS Group',

  // =========================
  // Luxury / High-End Developers
  // =========================
  'Oberoi Realty',
  'Lodha',
  'Lodha Group',
  'Trump Organization',
  'TARC',
  'Birla Estates',
  'DLF Luxury',
  'Sobha Realty',
  'Godrej Properties',
  'Emaar India',
  'Adani Realty',
  'Central Park',
  'Conscient Infrastructure',
  'Whiteland Corporation',
  'Elan Group',
  'M3M India',
  'Max Estates',

  // =========================
  // Affordable / Mid-Income
  // =========================
  'Signature Global',
  'ROF Group',
  'JMS Group',
  'Pyramid Infratech',
  'Ashiana Housing',
  'Mahira Homes',
  'Raheja Developers',
  'Sare Homes',
  'HCBS Developments',
  'Ramprastha Group',
  'CHD Developers',
  'Supertech Limited',
  'Mapsko Group',
  'Ansal Housing',
  'BPTP Limited',
  'Vatika Group',

  // =========================
  // Commercial / Mixed-Use
  // =========================
  'M3M India',
  'DLF Limited',
  'Elan Group',
  'AIPL',
  'Sapphire Builders',
  'Bestech Group',
  'Spaze Group',
  'SS Group',
  'Vatika Group',
  'Emaar India',
  'Adani Realty',
  'Smartworld Developers',
  'Central Park',
  'IREO',
  'Pioneer Urban',
  'Ambience Group',
  'Baani Group',

  // =========================
  // Sohna / South Gurgaon
  // =========================
  'Central Park',
  'Signature Global',
  'Ganga Realty',
  'Ashiana Housing',
  'GLS Infratech',
  'JMS Group',
  'ROF Group',
  'Pyramid Infratech',
  'Raheja Developers',
  'Suncity Projects',
  'HCBS Developments',
  'Trehan Group',
  'Max Estates',
  'Whiteland Corporation',
  'Aarcity Group',
  'Silverglades',
  'Krisumi Corporation',

  // =========================
  // Builder Floor / Local Developers
  // =========================
  'DGS Group',
  'Suncity',
  'Breez Builders',
  'Breez Global Heights',
  'GLS Infratech',
  'Spire Group',
  'Apex Buildwell',
  'JMS Group',
  'Pyramid Group',
  'Mahira Group',
  'HCBS',
  'VSR Ventures',
  'Adore Realtech',
  'Sare Homes',
  'Baani Group',
  'Global Group',
  'Landmark Group',
  'Alpha Corp',
  'Ramprastha Group',
  'Pioneer Urban',
  'Mapsko',
  'CHD Developers',

  // =========================
  // Other Developers / NCR Presence
  // =========================
  'Amrapali Group',
  'Jaypee Group',
  'ATS Homekraft',
  'Ace Group',
  'Civitech Developers',
  'Gulshan Group',
  'Saya Homes',
  'County Group',
  'CRC Group',
  'TVS Emerald',
  'Puravankara Limited',
  'Embassy Group',
  'Prestige Group',
  'Godrej Housing Finance',
] as const

export const BEDROOM_OPTIONS = [
  { value: 0, label: 'Studio' },
  { value: 1, label: '1 BHK' },
  { value: 2, label: '2 BHK' },
  { value: 3, label: '3 BHK' },
  { value: 4, label: '4 BHK' },
  { value: 5, label: '5+ BHK' },
] as const

export const BATHROOM_OPTIONS = [
  { value: 1, label: '1 Bathroom' },
  { value: 2, label: '2 Bathrooms' },
  { value: 3, label: '3 Bathrooms' },
  { value: 4, label: '4 Bathrooms' },
  { value: 5, label: '5+ Bathrooms' },
] as const

export const AREA_SQFT_OPTIONS = [
  450, 550, 650, 750, 850, 1000, 1150, 1250, 1400, 1600, 1800, 2000, 2200, 2500, 3000, 3500, 4000, 5000,
] as const

export const PRICE_OPTIONS = [
  { value: 2500000, label: '₹25 Lakhs' },
  { value: 3500000, label: '₹35 Lakhs' },
  { value: 5000000, label: '₹50 Lakhs' },
  { value: 7500000, label: '₹75 Lakhs' },
  { value: 10000000, label: '₹1 Crore' },
  { value: 12500000, label: '₹1.25 Crore' },
  { value: 15000000, label: '₹1.5 Crore' },
  { value: 20000000, label: '₹2 Crore' },
  { value: 25000000, label: '₹2.5 Crore' },
  { value: 30000000, label: '₹3 Crore' },
  { value: 40000000, label: '₹4 Crore' },
  { value: 50000000, label: '₹5 Crore' },
  { value: 75000000, label: '₹7.5 Crore' },
  { value: 100000000, label: '₹10 Crore+' },
] as const

export const ROI_OPTIONS = [
  { value: 0, label: 'Not Applicable' },
  { value: 5, label: '5% ROI' },
  { value: 6, label: '6% ROI' },
  { value: 7, label: '7% ROI' },
  { value: 8, label: '8% ROI' },
  { value: 9, label: '9% ROI' },
  { value: 10, label: '10% ROI' },
  { value: 12, label: '12% ROI' },
  { value: 15, label: '15% ROI' },
] as const

export const RERA_STATUS_OPTIONS = [
  'Project Registered',
  'Unit Registered',
  'Registration In Progress',
  'Not Applicable',
] as const

export const POSSESSION_QUARTERS = [
  'Ready to Move',
  'Q1 2026',
  'Q2 2026',
  'Q3 2026',
  'Q4 2026',
  'Q1 2027',
  'Q2 2027',
  'Q3 2027',
  'Q4 2027',
  'Q1 2028',
] as const

/** Include a legacy free-text value when editing older listings. */
export function withLegacyOption<T extends string>(
  options: readonly T[],
  current?: string | null,
): { value: string; label: string }[] {
  const mapped = options.map((value) => ({ value, label: value }))
  if (current && !options.includes(current as T)) {
    return [{ value: current, label: current }, ...mapped]
  }
  return mapped
}
